### ISSUE TITLE
Web Support ?

### ISSUE THREAD

**Issue by fortezhuo** [artyorsh/react-native-eva-icons#17]
Hi, I have tried to use UI kitten on RNW / Next JS. and an error occurs while integrate with Eva Icons

```
ReferenceError: Cannot access 'React' before initialization
./node_modules/react-native-eva-icons/icons/Github.js
/_next/development/server/static/development/pages/index.js:18566:13
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
module.exports../node_modules/react-native-eva-icons/icons/index.js.exports.findIconByName
./lib/icons/index.ts:693
  690 |     return require('./PersonOutline').default;
  691 | case 'person-remove':
  692 |     return require('./PersonRemove').default;
> 693 | case 'person-remove-outline':
      | ^  694 |     return require('./PersonRemoveOutline').default;
  695 | case 'phone':
  696 |     return require('./Phone').default;
```

**Comment by artyorsh** [comment]
Hi @fortezhuo 👋
I guess with a proper webpack configuration it can be runnable. We use this lib to build icons module for [react-native-ui-kitten](https://github.com/akveo/react-native-ui-kitten), where we have a playground application that is runnable in web. It is built on top of the Expo client, but it works in scope of this application. 

Will try to figure out proper webpack config for non-expo apps (did you managed to resolve this?). Thanks for the interest

**Comment by ghmeec** [comment]
Getting the same error here @fortezhuo  found solution to that already?

**Comment by fortezhuo** [comment]
@ghmeec ,
sorry for late response.. eventually I am using matured library icon like react native vector icons for boosting my project delivery time

**Comment by r17x** [comment]
I have been try use `react-native-eva-icons` with `react-native-web` but `jsx` didn't compile to `plain javascript` 
![Screenshot_20200118_153956](https://user-images.githubusercontent.com/16365952/72661097-f6069f80-3a08-11ea-849a-16e135ec2ea3.png)

Because of `jsx` not transpile to `javascript`, `react-scripts` can run my project with `react-native-eva-icons`. 

@artyorsh 

Thanks.

**Comment by artyorsh** [comment]
@ri7nz Done in [v.1.3.0](https://github.com/artyorsh/react-native-eva-icons/blob/master/CHANGELOG.md#130-2020-01-19). Thanks

**Comment by r17x** [comment]
@artyorsh thank you so much.
