### ISSUE TITLE
Outline icons ?

### ISSUE THREAD

**Issue by GabeConsalter** [artyorsh/react-native-eva-icons#19]
I can't set my icon to outline version.

To make this I had to set so many params:
```jsx
<Icon name="home" stroke={tintColor} strokeWidth={1} fillOpacity={0} width={24} height={24} />
```
And this does not render the outline real version, of course.

Isn't there a parameter that configures me the type of icon?
Some param like `outline={true}`

I may be doing it the wrong way.

**Comment by artyorsh** [comment]
Sorry for the late reply. This lib doesn't have separate prop to make an icon filled or outline. Instead, you can achieve this by passing `-outline` to `name` property.

```js
<Icon name='home-outline' />
```

**Comment by GabeConsalter** [comment]
All right. Make sense.

Thank you man.
