### ISSUE TITLE
How can i add custom svgs to your lib?

### ISSUE THREAD

**Issue by borstessi** [artyorsh/react-native-eva-icons#21]
## 💬 Question

Hey there, i really love your icons and i started using them. But i need some more icons for my own purpose. Is there an easy way to do that? Like saving some svgs somewhere and implement them with a line of code?

## React Native Eva Icons Version
newest..

**Comment by artyorsh** [comment]
@sanborN93 no. This library uses the original [eva-icons](https://github.com/akveo/eva-icons) as devDependency and launches a script for parsing the original svg to [react-native-svg](https://github.com/react-native-community/react-native-svg). What you-re using in production - is a generated code.
