### ISSUE TITLE
How to optimize? 

### ISSUE THREAD

**Issue by r17x** [artyorsh/react-native-eva-icons#23]
## 💬 Question
Do you have any information for make `react-native-eva-icons` is optimized use for `bundler` like webpack or facebook/metro ?

## React Native Eva Icons Version
- Version: `1.3.0`
   
## Example Bundle of `react-native-icon`
The real fact, I'm just use 1 Icon from `react-native-icons`. After finished bundling, the output `bundle` of my project it's lot an `unused`.

![image](https://user-images.githubusercontent.com/16365952/77033611-4cc53100-69da-11ea-86b7-748aa438de2a.png)

**Comment by gianpaj** [comment]
Same here. Is there a way to use a babel plugin like what they do with antd?
https://github.com/ant-design/babel-plugin-import

**Comment by artyorsh** [comment]
@gianpaj am I right that moving to direct imports should solve this? Because the same approach is used in the plugin you recommend
https://github.com/artyorsh/react-native-eva-icons#usage

**Comment by gianpaj** [comment]
That should work, thanks. But I'm using a package and itself uses RN-eva-icons (react-native-ui-kitten)

And for some reason, I believe all the Icons are bundled 
https://github.com/akveo/react-native-ui-kitten/blob/master/src/eva-icons/index.ts

**Comment by artyorsh** [comment]
@gianpaj Then I guess this is not the issue for this library.

But in case of using `@ui-kitten/eva-icons` package, you might want to follow [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#3rd-party-icon-packages) and write your own icon package that reduces using proxies (like it is currently implemented) in favor of direct imports.

See _3rd party Icon packages_ section.
